### ISSUE TITLE
Missing dependencie

### ISSUE THREAD

**Issue by MarcelCossijns** [gbrlsnchs/material2-carousel#13]
`import {BrowserAnimationsModule} from '@angular/platform-browser/animations';`

```
@NgModule({
  ...
  export: [
    ...    
    BrowserAnimationsModule
  ],
  ...
})
```

**Comment by gbrlsnchs** [comment]
Sorry, I don't get what's the problem. Would you mind elaborating the issue a bit better? Thanks!
