### ISSUE TITLE
Allow to set custom height

### ISSUE THREAD

**Issue by MuresanVladMihail** [gbrlsnchs/material2-carousel#30]
Right now the only way to modify the height of the rendered list of a ```mat-carousel``` is to modify the ```proportion```, this is very bad. 
In conclusion, I think this is __garbage__, I mean why would you adjust the bottom padding based on the ```[proportion]``` and not on height??.

**Comment by gbrlsnchs** [comment]
Hello, the idea behind proportion is to adjust the carousel's height based on its width, this way making it responsive while preventing cutting the image displayed.

However, if you think this is **garbage** enough, I'd be willing to review and merge a PR to enhance this. :smiley_cat:

**Comment by chriswnewman** [comment]
@gbrlsnchs I've opened a PR #31 which addresses this issue. let me know if you have any questions or would like to discuss implementation details

**Comment by gbrlsnchs** [comment]
Oh, well, I think I missed that one. Thanks for the notification. I will check it ASAP. Thanks again!
