### ISSUE TITLE
Ivy broke carousel?

### ISSUE THREAD

**Issue by fritzschoff** [gbrlsnchs/material2-carousel#34]
I recently upgraded to ivy because of production reasons. And the carousel was working perfectly fine, but after the upgrade, it is in the DOM but the slides won't show up.
Can it be that ivy and the bug I experiences are related?

**Comment by Cayan** [comment]
It is working well for me. I had to make some changes to properly support the latest material version.
https://github.com/gbrlsnchs/material2-carousel/pull/35

**Comment by Cayan** [comment]
What settings are you using? I tested with the default ones, maybe the ones you are using are not compatible.

**Comment by fritzschoff** [comment]
I found a solution. I had an ng container around the mat-slide-component cause I had another *ng directive on the mat-slide. But I did the *ngFor on the mat-slide-component and it worked. Not sure how ivy was evolved with it, but this was the only update I made since it was broken...

**Comment by gabrieltaets** [comment]
For me it broke only when I tried to update Material to v9 because it now requires deep imports. After rolling back to v8 it is working fine.
