### ISSUE TITLE
Demo of stackblitz

### ISSUE THREAD

**Issue by sarowerj** [gbrlsnchs/material2-carousel#40]
Can anyone make a demo in stackblitz. Some how I can't use this ..

Thanks

**Comment by mmoiroux** [comment]
I just found this : https://gsr.dev/material2-carousel/

**Comment by gbrlsnchs** [comment]
As pointed by @mmoiroux, there is the official demo. If you want to see the code for it, check [its source code](https://github.com/gbrlsnchs/material2-carousel/tree/master/projects/demo/src).
