### ISSUE TITLE
Gestures not working and warning in console.

### ISSUE THREAD

**Issue by gabrielbusarello** [gbrlsnchs/material2-carousel#50]
Hi!

In your example I can use gestures for change the sliders.

But it's not working in the Angular 9. Then I see an warning in console.
![Captura de Tela 2020-02-22 às 20 13 04](https://user-images.githubusercontent.com/25415068/75100704-22857c80-55b0-11ea-84a2-3f3eb8c46414.png)

I think this is what is causing the problem. If was that, I can do some tests, and submit a PR.

**Comment by gbrlsnchs** [comment]
This is a dup of https://github.com/gbrlsnchs/material2-carousel/issues/44, let's track it there.
