### ISSUE TITLE
The library needs to update its dependencies, correct classes and repair the problem that gestures do not work

### ISSUE THREAD

**Issue by sawa-ko** [gbrlsnchs/material2-carousel#51]
The library is outdated with the latest Angular dependencies so it generates Log in the browser console with warnings, also npm says that Angular Material is outdated. Please update the library.

This is the warning that shows in the console of the nevagador when using the library.
![75100704-22857c80-55b0-11ea-84a2-3f3eb8c46414](https://user-images.githubusercontent.com/56084970/75116358-25728280-562d-11ea-8baa-46af578f5274.png)
Also the gestures are not working.

**Comment by gbrlsnchs** [comment]
This is a dup of https://github.com/gbrlsnchs/material2-carousel/issues/44, let's track it there.
